[package]
name = "pid"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
up-safe-cell = { git = "https://github.com/binary-bruce/up-safe-cell" }
